language: node_js
sudo: required
addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
services:
  - docker
node_js:
  - 11
before_install:
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/framework.git unitejs/unitejs-framework
  - cd unitejs/unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/cli-core.git unitejs/unitejs-cli-core
  - cd unitejs/unitejs-cli-core
  - npm link unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/packages.git unitejs/unitejs-packages
  - cd unitejs/unitejs-packages
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/engine.git unitejs/unitejs-engine
  - cd unitejs/unitejs-engine
  - npm link unitejs-framework unitejs-packages
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/image.git unitejs/unitejs-image
  - cd unitejs/unitejs-image
  - npm link unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/image-cli.git unitejs/unitejs-image-cli
  - cd unitejs/unitejs-image-cli
  - npm link unitejs-framework unitejs-cli-core unitejs-image
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/cli.git unitejs/unitejs-cli
  - cd unitejs/unitejs-cli
  - npm link unitejs-framework unitejs-cli-core unitejs-engine
  - cd ../../
  - npm install -g gulp
  - npm install -g cordova
  - node unitejs/unitejs-cli/bin/unite configure --packageName=vue-typescript --title="Vue TypeScript" --profile=VueTypeScript --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite generate --type=class --name=MyClass --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite generate --type=component --name=MyComponent --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite generate --type=enum --name=MyEnum --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite generate --type=interface --name=MyInterface --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite platform --operation=add --platformName=Cordova --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite platform --operation=add --platformName=Docker --outputDirectory=./app
  - node unitejs/unitejs-cli/bin/unite platform --operation=add --platformName=Electron --outputDirectory=./app
  - cd ./app/www
install:
  - npm link unitejs-image
  - npm install
script: 
  - gulp build || travis_terminate 1
  - gulp theme-build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp e2e-install --drivers=chrome || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp build --buildConfiguration=prod || travis_terminate 1
  - gulp e2e || travis_terminate 1
  - gulp doc-build || travis_terminate 1
  - gulp platform-web-package --buildConfiguration=prod || travis_terminate 1
  - gulp platform-electron-dev || travis_terminate 1
  - gulp platform-electron-package --buildConfiguration=prod || travis_terminate 1
  - gulp platform-docker-package --buildConfiguration=prod || travis_terminate 1
  - gulp platform-cordova-dev --buildConfiguration=prod || travis_terminate 1
  - gulp platform-cordova-theme --buildConfiguration=prod || travis_terminate 1
